<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$assetRepo = $objectManager->get('Magento\Framework\View\Asset\Repository');
$ame_logo = $assetRepo->getUrl("Tatix_PIX::images/ame-logo.png");

$checkoutSession = $objectManager->get('Magento\Checkout\Model\Session');
$grandTotal = $checkoutSession->getQuote()->getGrandTotal();
$api = $objectManager->get('Aditum\Payment\Helper\API');
$cashbackValue = $grandTotal * $cashbackPercent * 0.01;

$cashback_text = "";

$cashback_text = "&nbsp;&nbsp;Receba R$".number_format($cashbackValue,"2",",",".")." de volta com a AME Digital";
?>
<div id="ameLogoHtml" style="display: none;"><?php echo $ame_logo; ?></div>
<div id="cashbackTxtHtml" style="display: none;"><?php echo $cashback_text; ?></div>
