<?php
/**
 * @var \AditumPayment\Magento2\Block\PixSuccess $block
 */

if ($block->getPaymentMethod() === "aditumpix"):
    ?>
    <p>
        Realize o pagamento diretamente no seu aplicativo de pagamentos ou Internet Banking, para isso, escaneie o QR code abaixo:
    </p>
    <p>
        <img src="<?=$block->getQrCodeUrl()?>">
    </p>
    <p>Ou se preferir, copie e cole o código abaixo:</p>
    <p><input id="copyTarget" type="text" size="100" class="input-text" value="<?=$block->getQrCodeTxt()?>" readonly="readonly"></p>
    <button id="copyButton"  class="action primary continue">
        <?php echo __('Copy') ?>
    </button>
    <script type="text/javascript">
        document.getElementById("copyButton").addEventListener("click", function() {
            copyToClipboard(document.getElementById("copyTarget"));
        });

        function copyToClipboard(elem) {
            // create hidden text element, if it doesn't already exist
            var targetId = "_hiddenCopyText_";
            var isInput = elem.tagName === "INPUT" || elem.tagName === "TEXTAREA";
            var origSelectionStart, origSelectionEnd;
            if (isInput) {
                // can just use the original source element for the selection and copy
                target = elem;
                origSelectionStart = elem.selectionStart;
                origSelectionEnd = elem.selectionEnd;
            } else {
                // must use a temporary form element for the selection and copy
                target = document.getElementById(targetId);
                if (!target) {
                    var target = document.createElement("textarea");
                    target.style.position = "absolute";
                    target.style.left = "-9999px";
                    target.style.top = "0";
                    target.id = targetId;
                    document.body.appendChild(target);
                }
                target.textContent = elem.textContent;
            }
            // select the content
            var currentFocus = document.activeElement;
            target.focus();
            target.setSelectionRange(0, target.value.length);

            // copy the selection
            var succeed;
            try {
                succeed = document.execCommand("copy");
            } catch(e) {
                succeed = false;
            }
            // restore original focus
            if (currentFocus && typeof currentFocus.focus === "function") {
                currentFocus.focus();
            }

            if (isInput) {
                // restore prior selection
                elem.setSelectionRange(origSelectionStart, origSelectionEnd);
            } else {
                // clear temporary content
                target.textContent = "";
            }
            return succeed;
        }
    </script>

<?php endif; ?>
